### ISSUE TITLE
Unable to build v6.3.0 for Android

### ISSUE THREAD

**Issue by short-dsb** [lottie-react-native/lottie-react-native#1105]
### Description

Android build fails with v6.3.0. Works with the previous release, v6.2.0.

Looks like it’s missing this line in `LottieAnimationViewPropertyManager.kt`, as it compiles successfully after adding it:

```java
import android.net.Uri
```

### Steps to Reproduce

1. `npm run android`

**Expected behavior:** [What you expected to happen]

Build completes successfully.

**Actual behavior:** [What actually happened]

> e: node_modules/lottie-react-native/android/src/main/java/com/airbnb/android/react/lottie/LottieAnimationViewPropertyManager.kt: (99, 40): Unresolved reference: Uri

### React Native Environment

```yaml
System:
  OS: macOS 13.5.2
  CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
  Memory: 233.12 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.17.0
    path: ~/.nvm/versions/node/v18.17.0/bin/node
  Yarn: Not Found
  npm:
    version: 9.6.7
    path: ~/.nvm/versions/node/v18.17.0/bin/npm
  Watchman:
    version: 2023.08.07.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/<user>/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/<user>/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Lottie Version

Version: 6.3.0
